import { activeSession, activeWindow, makeSession, makeState, makeWindow, tmuxKey, type TmuxState } from './tmuxModel';
export interface TmuxExercise {initial:TmuxState;task:string;steps:string[];goal(state:TmuxState):boolean}
export interface TmuxLesson {id:string;group:string;title:string;description:string;tip:string;make(variation:number):TmuxExercise}
const names=['ghost','wisp','phantom','specter'];
export const tmuxGroups=['Sessions','Windows','Panes','Help & history'];
export const tmuxGroupPurpose:Record<string,string>={
  Sessions:'project containers',
  Windows:'full-screen tabs',
  Panes:'visible splits',
  'Help & history':'inspect and discover',
};
export const tmuxWhy:Record<string,string>={
  'new-session':'Use one session per project or long-running job so its terminal work can be detached and resumed together.',
  detach:'Leave the terminal without stopping the programs inside the session.',
  'list-sessions':'Find resumable work before deciding whether to create another session.',
  attach:'Continue the same programs and layout after opening another terminal or reconnecting.',
  'reattach-cycle':'Build the recovery routine that makes tmux useful after a terminal or SSH interruption.',
  'new-or-attach':'Use one reliable command whether the named session already exists or not.',
  'rename-session':'Recognize projects quickly when several sessions are running.',
  'switch-session':'Move between separate projects without ending either one.',
  'kill-session':'End an entire finished workspace and all programs it contains.',
  'new-window':'Create another full-terminal workspace inside this session when a task needs more room than a split pane.',
  'next-window':'Use windows like tabs when each task needs the whole terminal. n changes which window fills the screen; it does not move between split panes.',
  'previous-window':'Return to the preceding full-terminal window while programs in the other windows keep running.',
  'number-window':'Jump straight to a known full-terminal window instead of stepping through the list.',
  'rename-window':'Make the status-line window list describe each full-screen task.',
  'close-window':'Remove one finished full-terminal workspace without ending the rest of the session.',
  'split-right':'Use panes when two programs need to stay visible at once, such as code beside logs. Both panes belong to the current window.',
  'split-down':'Stack two visible terminals inside the current window when vertical space suits the work.',
  'focus-pane':'Choose which visible pane receives your typing without changing windows.',
  'cycle-pane':'Move through visible panes quickly when direction does not matter.',
  'zoom-pane':'Temporarily give one pane the full window, then restore the split layout.',
  'close-pane':'End one visible terminal while preserving the other panes and windows.',
  'key-help':'Discover the bindings available in the current tmux configuration.',
  'scroll-history':'Read output that has scrolled out of view without disturbing the running program.',
  'command-prompt':'Run tmux management commands without detaching to the outside shell.',
};
export const expandTmux=(steps:string[])=>steps.flatMap(step=>step.startsWith('type:')?[...step.slice(5)]:[step]);
const seen=(s:TmuxState,event:string)=>s.events.includes(event);
const withWindows=(name:string)=>{const s=makeState(name);s.sessions[0].windows=[makeWindow(0,'editor'),makeWindow(1,'logs'),makeWindow(2,'shell')];return s;};
const withPanes=(name:string)=>{const s=tmuxKey(tmuxKey(makeState(name),'Ctrl+b'),'%');s.events=[];s.log=[];s.sessions[0].windows[0].panes[0].program='lantern watch · running';return s;};
export const tmuxLessons:TmuxLesson[]=[
  {id:'new-session',group:'Sessions',title:'A home for your running spells',description:'Start tmux from an ordinary shell. A named session groups your windows and keeps their programs running when you detach.',tip:'Type tmux new -s followed by the session name, then Enter. The -s flag names the new session.',make(v){const name=names[v],initial=makeState(name,false);initial.sessions=[];return {initial,task:`Create and enter a session named ${name}.`,steps:[`type:tmux new -s ${name}`,'Enter'],goal:s=>seen(s,'create')&&s.attached===name};}},
  {id:'detach',group:'Sessions',title:'Step outside; leave the light on',description:'Detach returns this terminal to its outside shell. Your tmux session and its programs continue running on the same machine.',tip:'Hold Ctrl and press b together. Release both, then press d alone. Do not use exit: that closes the pane shell.',make(v){const name=names[v],initial=makeState(name);initial.sessions[0].windows[0].panes[0].program='lantern watch · running';return {initial,task:'Detach while keeping the lantern watch and its session alive.',steps:['Ctrl+b','d'],goal:s=>seen(s,'detach')&&s.attached===null&&s.sessions[0]?.windows[0]?.panes[0]?.program==='lantern watch · running'};}},
  {id:'list-sessions',group:'Sessions',title:'Find the rooms you left behind',description:'tmux ls lists existing sessions from the shell. Use it when you have forgotten a session name before attaching.',tip:'The shell command is tmux ls, followed by Enter. A detached session can still have running programs.',make(v){const initial=makeState(names[v],false);initial.sessions.push(makeSession('pumpkin'));return {initial,task:'List both detached sessions without entering or closing either.',steps:['type:tmux ls','Enter'],goal:s=>seen(s,'list')&&s.attached===null&&s.sessions.length===2};}},
  {id:'attach',group:'Sessions',title:'Return to the same little room',description:'tmux attach -t NAME reconnects your terminal to an existing session. You return to its windows and programs instead of starting over.',tip:'Use the exact name shown in the session list. On a remote machine, reconnect with SSH to that machine first, then attach there.',make(v){const name=names[v],initial=withPanes(name);initial.attached=null;return {initial,task:`Attach to ${name} and recover its two panes.`,steps:[`type:tmux attach -t ${name}`,'Enter'],goal:s=>seen(s,'attach')&&s.attached===name&&activeWindow(s)?.panes.length===2};}},
  {id:'reattach-cycle',group:'Sessions',title:'A lantern that waits for you',description:'Practice the complete leave-and-return routine: detach, inspect existing sessions, then attach to the same one.',tip:'After Ctrl+b then d, you are outside tmux. Run tmux ls, then tmux attach -t NAME. Detaching is not saving to disk or surviving a reboot.',make(v){const name=names[v],initial=withPanes(name);return {initial,task:`Leave ${name}, list sessions, and return with both panes still running.`,steps:['Ctrl+b','d','type:tmux ls','Enter',`type:tmux attach -t ${name}`,'Enter'],goal:s=>['detach','list','attach'].every(event=>seen(s,event))&&s.attached===name&&activeWindow(s)?.panes.length===2};}},
  {id:'new-or-attach',group:'Sessions',title:'One command to come home',description:'tmux new -A -s NAME attaches if that named session exists, or creates it if it does not.',tip:'Capital -A means attach to an existing session. Without it, trying to create the same named session again reports a duplicate.',make(v){const name=names[v],initial=makeState(name,false);if(v%2===0)initial.sessions=[];return {initial,task:`Enter ${name}, creating it only if needed.`,steps:[`type:tmux new -A -s ${name}`,'Enter'],goal:s=>(seen(s,'create')||seen(s,'attach'))&&s.attached===name&&s.sessions.length===1};}},
  {id:'rename-session',group:'Sessions',title:'Put a name on the haunted door',description:'Ctrl+b then $ opens the session-name prompt. A clear name makes the right session easier to find later.',tip:'The prompt contains the current name. Ctrl+u clears it; type the new name and press Enter.',make(v){const name=names[v],target=name+'-den';return {initial:makeState(name),task:`Rename this session to ${target}.`,steps:['Ctrl+b','$','Ctrl+u',`type:${target}`,'Enter'],goal:s=>seen(s,'rename-session')&&s.attached===target};}},
  {id:'switch-session',group:'Sessions',title:'Visit the pumpkin next door',description:'Ctrl+b then s opens a session chooser inside tmux. Move to another session and press Enter to switch this client to it.',tip:'The exercise shows two session rows. Down selects the second; Enter attaches to it. The first session stays alive.',make(v){const initial=makeState(names[v]);initial.sessions.push(makeSession('pumpkin'));return {initial,task:'Switch to pumpkin through the session chooser, keeping both sessions.',steps:['Ctrl+b','s','ArrowDown','Enter'],goal:s=>seen(s,'switch-session')&&s.attached==='pumpkin'&&s.sessions.length===2};}},
  {id:'kill-session',group:'Sessions',title:'Close a finished haunt deliberately',description:'tmux kill-session -t NAME ends that session and all its programs. This is for finished work; detach when you want to return later.',tip:'This exercise only removes a simulated session. Target its name carefully; the other session must remain.',make(v){const name=names[v],initial=makeState(name,false);initial.sessions.push(makeSession('pumpkin'));return {initial,task:`End the finished ${name} session, keeping pumpkin.`,steps:[`type:tmux kill-session -t ${name}`,'Enter'],goal:s=>seen(s,'kill-session')&&s.sessions.length===1&&s.sessions[0].name==='pumpkin'};}},
  {id:'new-window',group:'Windows',title:'Another room in the same haunt',description:'A window is like a terminal tab within a session. Ctrl+b then c creates and selects a new window.',tip:'Your old window keeps running. The status bar shows both windows; * marks the current one.',make(v){return {initial:makeState(names[v]),task:'Create a second window in this session.',steps:['Ctrl+b','c'],goal:s=>activeSession(s)?.windows.length===2&&activeSession(s)?.active===1};}},
  ...(['n','p'] as const).map((key):TmuxLesson=>({id:key==='n'?'next-window':'previous-window',group:'Windows',title:key==='n'?'Follow the next lantern':'Return to the previous lantern',description:`Ctrl+b then ${key} selects the ${key==='n'?'next':'previous'} full-screen window, like changing tabs. Navigation wraps around the window list.`,tip:'These keys switch tmux windows, not panes. To focus a visible split pane, use Ctrl+b then an arrow key or o.',make(v){const initial=withWindows(names[v]);initial.sessions[0].active=1;return {initial,task:`Switch from logs to ${key==='n'?'shell':'editor'}.`,steps:['Ctrl+b',key],goal:s=>seen(s,'switch-window')&&activeSession(s)?.active===(key==='n'?2:0)};}})),
  {id:'number-window',group:'Windows',title:'Go straight to room zero',description:'Ctrl+b then a digit selects that window index directly. Default tmux starts numbering windows at zero.',tip:'Use the number in the status bar. Custom configurations can change the base index; this course uses tmux defaults.',make(v){const initial=withWindows(names[v]);initial.sessions[0].active=2;return {initial,task:'Select window 0, editor, directly.',steps:['Ctrl+b','0'],goal:s=>seen(s,'switch-window')&&activeSession(s)?.active===0};}},
  {id:'rename-window',group:'Windows',title:'A label for your lantern logs',description:'Ctrl+b then comma renames the current window. Use names that describe the work inside.',tip:'Clear the existing name with Ctrl+u, type the new label, then Enter. Session rename uses $ instead of comma.',make(v){const target=names[v]+'-logs';return {initial:makeState(names[v]),task:`Rename this window to ${target}.`,steps:['Ctrl+b',',','Ctrl+u',`type:${target}`,'Enter'],goal:s=>seen(s,'rename-window')&&activeWindow(s)?.name===target};}},
  {id:'close-window',group:'Windows',title:'Finish a room, keep the house',description:'Ctrl+b then & asks to close the current window and all its panes. Confirm with y, or cancel with n.',tip:'This is stronger than detaching. The exercise keeps two other windows alive so you can see the difference.',make(v){const initial=withWindows(names[v]);initial.sessions[0].active=1;return {initial,task:'Close the finished logs window, keeping editor and shell.',steps:['Ctrl+b','&','y'],goal:s=>seen(s,'close-window')&&activeSession(s)?.windows.length===2&&!activeSession(s)?.windows.some(w=>w.id===1)};}},
  ...(['%','"'] as const).map((key):TmuxLesson=>({id:key==='%'?'split-right':'split-down',group:'Panes',title:key==='%'?'Two ghosts side by side':'A lantern above, a shell below',description:`Ctrl+b then ${key} splits the active pane ${key==='%'?'left and right':'top and bottom'}. Each pane has its own terminal and program.`,tip:key==='%'?'% makes a left/right split. The new pane becomes active; the original program keeps running beside it.':'The double quote makes a top/bottom split. Type the quote key after releasing Ctrl+b.',make(v){return {initial:makeState(names[v]),task:`Split this window into two ${key==='%'?'side-by-side':'stacked'} panes.`,steps:['Ctrl+b',key],goal:s=>seen(s,key==='%'?'split-right':'split-down')&&activeWindow(s)?.panes.length===2};}})),
  {id:'focus-pane',group:'Panes',title:'Look back toward the lantern',description:'Ctrl+b followed by an arrow key selects the pane in that direction. The active border shows where your typing will go.',tip:'From the right pane, use Ctrl+b then Left. The lantern watch keeps running in the other pane while you move.',make(v){return {initial:withPanes(names[v]),task:'Focus the left pane running lantern watch.',steps:['Ctrl+b','ArrowLeft'],goal:s=>seen(s,'focus-pane')&&activeWindow(s)?.active===0};}},
  {id:'cycle-pane',group:'Panes',title:'Let each little ghost take a turn',description:'Ctrl+b then o cycles to the next pane. It is handy when you want to move through panes without choosing a direction.',tip:'The pane border moves; no program is stopped. In this two-pane window, o wraps from the right pane to the left.',make(v){return {initial:withPanes(names[v]),task:'Cycle from the right pane to the lantern pane.',steps:['Ctrl+b','o'],goal:s=>seen(s,'focus-pane')&&activeWindow(s)?.active===0};}},
  {id:'zoom-pane',group:'Panes',title:'A closer look, then room for both',description:'Ctrl+b then z toggles zoom for the active pane. Other panes keep running while hidden; repeat to restore the layout.',tip:'Press Ctrl+b then z twice, with a fresh prefix each time. Zoom changes the view, not the number of panes.',make(v){return {initial:withPanes(names[v]),task:'Zoom the current pane, then restore the two-pane layout.',steps:['Ctrl+b','z','Ctrl+b','z'],goal:s=>seen(s,'zoom-in')&&seen(s,'zoom-out')&&activeWindow(s)?.panes.length===2&&!activeWindow(s)?.zoom};}},
  {id:'close-pane',group:'Panes',title:'Put one finished shell to rest',description:'Ctrl+b then x asks to close only the active pane. Confirm with y; n cancels. Closing the last pane also closes its window.',tip:'Keep the left lantern watch running. Close the right shell only. Use detach instead when you want all programs to survive.',make(v){return {initial:withPanes(names[v]),task:'Close the right shell pane while keeping the lantern watch alive.',steps:['Ctrl+b','x','y'],goal:s=>seen(s,'close-pane')&&activeWindow(s)?.panes.length===1&&activeWindow(s)?.panes[0].program==='lantern watch · running'};}},
  {id:'key-help',group:'Help & history',title:'Ask the spellbook for a shortcut',description:'Ctrl+b then ? shows tmux key bindings. Press q without a prefix to return to your terminal.',tip:'The simulation shows the common bindings taught here. Real tmux displays its full binding list, including your customizations.',make(v){return {initial:makeState(names[v]),task:'Open the shortcut list, then close it with q.',steps:['Ctrl+b','?','q'],goal:s=>seen(s,'help-open')&&seen(s,'help-close')};}},
  {id:'scroll-history',group:'Help & history',title:'Read the lantern’s earlier whispers',description:'Ctrl+b then [ enters copy mode to inspect terminal history. Arrow keys move through it; q returns to live output.',tip:'Move up twice, then q. Copy-selection bindings depend on mode-keys (emacs or vi); this first drill uses the shared arrow and q keys.',make(v){return {initial:makeState(names[v]),task:'Enter history, move up two lines, then return to the live terminal.',steps:['Ctrl+b','[','ArrowUp','ArrowUp','q'],goal:s=>seen(s,'copy-close')&&s.events.filter(e=>e==='scroll').length>=2};}},
  {id:'command-prompt',group:'Help & history',title:'Speak directly to the housekeeper',description:'Ctrl+b then : opens tmux’s command prompt. Here you type tmux commands without the leading word tmux.',tip:'At this prompt, enter list-sessions. From an ordinary shell, you would type tmux list-sessions instead. Esc cancels an unfinished prompt.',make(v){return {initial:makeState(names[v]),task:'List sessions through tmux’s own command prompt.',steps:['Ctrl+b',':','type:list-sessions','Enter'],goal:s=>seen(s,'list')&&s.attached===names[v]};}},
];
